### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by BiGUNMAN** [alphartdev/BungeeAdminTools#19] opened 2015-08-07 00:32 UTC
I mean, I never knew BungeeAdminTools was this amazing. I know its like beyond words of amazing, the solution to life.. But I never knew it was this:
http://i.imgur.com/jGvjsMk.png

When doing /lookup (player)

**Comment by alphartdev** [comment] 2015-08-09 11:46
This is a known issue, which I'm not able to fix. If you have any idea, feel free to send a PR.
Otherwise disable literal dates in your config.yml.

**Comment by OldTownMC** [comment] 2015-08-10 00:27
Oh okay, thanks!

**Comment by TheMattVid** [comment] 2015-08-11 05:59
Individual server logs have pretty accurate time. Would BAT somehow be able to tap into the same source of time as the server logs? Perhaps BAT can use the internal clock of the computer that it's running on. I don't know the plausibility of my ideas, but I'm just throwing them out there.

**Comment by alphartdev** [comment] 2015-09-06 11:29
Dates are actually working fine, the problem is that (for unknown reasons) I can't correctly convert 6th September to "today", sometimes it will convert to "tomorrow".

**Comment by Techcable** [comment] 2015-10-18 05:46
Probably timezones

**Comment by minecrafter** [comment] 2015-10-18 05:58
@Techcable It's more of a combination of BAT and MySQL not playing well with timezones.

I have a potential fix for this, but in the rewrite, I'm simply torn between supporting MySQL and its funny timezone business or storing the intended timezone and not letting the database modify it.

**Comment by Techcable** [comment] 2015-10-18 07:12
Just use a long for milliseconds in GMT time.
Only the user interface should know or care about timezones.

**Comment by YepImRobbie** [comment] 2016-11-23 23:39
It's not just /lookup for me - If I mute someone for ten seconds, it'll tell them they're unmuted 10 seconds later, but they can't speak until tomorrow. Same with bans, everything across the board.

What should I do?

**Comment by alphartdev** [comment] 2016-11-24 18:21
I answered your review on spigot.

**Closed by alphartdev** 2016-11-24 18:21 UTC
Labels: bug
