### ISSUE TITLE
Error after changing host

### ISSUE THREAD

**Issue by DanSpedey** [alphartdev/BungeeAdminTools#9] opened 2015-02-01 13:15 UTC
I just moved my dedicated server to a different timezone.

I believe this has something to do with the error caused? http://pastebin.com/YxwG8pB6
If not, what is the cause on BAT not connecting to my database?

Thanks!

**Comment by alphartdev** [comment] 2015-02-01 15:37
Yeah that's for sure the cause though you got a pretty weird error which looks like some misconfiguration (not sure on which side tho). I'm coming back to you once I investigate that

**Comment by DanSpedey** [comment] 2015-02-01 15:41
Thanks!

**Comment by DanSpedey** [comment] 2015-02-02 16:22
I just tried to create a new MySQL database, it is giving the same error when connecting to the empty one.

**Comment by alphartdev** [comment] 2015-02-02 17:08
Yeah, the problem is clearly between some kind of timezone incompatibilities so creating new db on the same server isn't probably affecting that. Actually, I'm trying to figure out if I can solve it on my side or if it's an configuration error.

**Comment by DanSpedey** [comment] 2015-02-02 19:38
Would you like me to pastebin my configurations?

**Comment by alphartdev** [comment] 2015-02-02 21:49
That's actually some java or mysql configuration not something directly related to BAT so there could be a lot of things to copy/paste :p As I said I'm trying to find a solution to this problem but it may take some time.

**Comment by alphartdev** [comment] 2015-02-04 17:01
Ok I just looked again and it seems to be a pretty uncommon error so here are a couple of questions : 
- which timezone does your mysql server use ? (Timezone of the dedicated server hosting it)
- which timezone does your Bungee server use ? (Timezone of the dedicated server hosting it)
- Which one did you move ?
Also could you update Java and MySQL please ? (if you're on linux, an "apt-get update", followed by an "apt-get upgrade" should do the trick)

**Comment by DanSpedey** [comment] 2015-02-06 17:22
I moved the timezone back to the one we had on the old server and it worked perfectly.

**Comment by alphartdev** [comment] 2015-02-06 17:48
That's some great new :D What do you mean by "moving the timezone", did you change the server settings ?

**Comment by DanSpedey** [comment] 2015-02-06 18:04
Yes i did

**Comment by alphartdev** [comment] 2015-02-07 11:40
Ok thanks for the tip so I consider it as a configuration issue and I close the issue.
Feel free to reopen it if you meet others errors related to timezone

**Closed by alphartdev** 2015-02-07 11:40 UTC
